networks:
  my-custom-network:
    external:
      name: bridge_proxy

services:
  threshold_frontend:
    image: threshold-frontend
    # networks:
    #  - my-custom-network
    ports:
      - "80:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  threshold_node_1:
    image: threshold-client
    networks:
      - my-custom-network
    environment:
      - BLSKEY=/app/key
      - MEMPOOLURL=mempool
      - APIPORT=8081
      - TOPICNAME=458005e1367b74db64262ef76cda4f631183651ecdd978c0e7dc02dd65d862f1
      - PRIVKEY=/app/sk
      - RPCURL=https://ethereum-holesky-rpc.publicnode.com/
      - CONTRACTADDR=0xA6E24910b506b387365E8C685B255EB3bfbFb5DC
      - PROXYPORT=8082
      - COMITTEESIZE=4
      - IPFSGATEWAYURL=https://moccasin-effective-harrier-491.mypinata.cloud
      - BEARERTOKEN=/app/bearertoken
    volumes:
      - ./threshold-encryption/keys/1-bls:/app/key
      - ./threshold-encryption/keys/1-ecdsa:/app/sk
    ports:
      - 8082:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"

  threshold_node_2:
    image: threshold-client
    networks:
      - my-custom-network
    environment:
      - BLSKEY=/app/key
      - MEMPOOLURL=mempool
      - APIPORT=8081
      - TOPICNAME=458005e1367b74db64262ef76cda4f631183651ecdd978c0e7dc02dd65d862f1
      - PRIVKEY=/app/sk
      - RPCURL=https://ethereum-holesky-rpc.publicnode.com/
      - CONTRACTADDR=0xA6E24910b506b387365E8C685B255EB3bfbFb5DC
      - PROXYPORT=8082
      - COMITTEESIZE=4
      - IPFSGATEWAYURL=https://moccasin-effective-harrier-491.mypinata.cloud
      - BEARERTOKEN=/app/bearertoken
    volumes:
      - ./threshold-encryption/keys/2-bls:/app/key
      - ./threshold-encryption/keys/2-ecdsa:/app/sk
    ports:
      - 8083:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"

  threshold_node_3:
    image: threshold-client
    networks:
      - my-custom-network
    environment:
      - BLSKEY=/app/key
      - MEMPOOLURL=mempool
      - APIPORT=8081
      - TOPICNAME=458005e1367b74db64262ef76cda4f631183651ecdd978c0e7dc02dd65d862f1
      - PRIVKEY=/app/sk
      - RPCURL=https://ethereum-holesky-rpc.publicnode.com/
      - CONTRACTADDR=0xA6E24910b506b387365E8C685B255EB3bfbFb5DC
      - PROXYPORT=8082
      - COMITTEESIZE=4
      - IPFSGATEWAYURL=https://moccasin-effective-harrier-491.mypinata.cloud
      - BEARERTOKEN=/app/bearertoken
    volumes:
      - ./threshold-encryption/keys/3-bls:/app/key
      - ./threshold-encryption/keys/3-ecdsa:/app/sk
    ports:
      - 8084:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"